# fly.toml app configuration file generated for spiff-backend on 2023-06-21T09:42:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
#https://documentation-git-fork-bogdaaamn-docs-fly-deplo-460c6b-strapijs.vercel.app/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/fly.html
#https://forum.strapi.io/t/fly-io-deployment/22438

app = "spiff-backend"
primary_region = "ams"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

[env]
  PORT="80"
  APP_URL="https://spiff-backend.fly.dev"
  DATABASE_HOST="db.aljboewzouwkmsskqugr.supabase.co"
  DATABASE_NAME="postgres"
  DATABASE_USERNAME="postgres"
  FTP_HOST = "ftp.spiff-radio.org"
  FTP_BASE_PATH = "/"
  FTP_BASE_URL = "https://v3.spiff-radio.org/uploads/"
