# fly.toml app configuration file generated for spiff-backend on 2023-06-21T09:42:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
#https://documentation-git-fork-bogdaaamn-docs-fly-deplo-460c6b-strapijs.vercel.app/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/fly.html
#https://forum.strapi.io/t/fly-io-deployment/22438

app = "spiff-backend"
primary_region = "ams"

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

#non-sensitive environment variables
  [env]
    APP_URL = "https://spiff-backend.fly.dev"
    PORT = "80"
    DATABASE_HOST = "db.aljboewzouwkmsskqugr.supabase.co"
    DATABASE_NAME="postgres"
    DATABASE_USERNAME="postgres"
    #DATABASE_PASSWORD as fly.io secret
